# Generated by Django 4.1 on 2022-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_alter_city_options_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="phone_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
