# Generated by Django 4.1 on 2022-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_alter_country_phone_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="iso_code",
            field=models.CharField(max_length=5),
        ),
    ]
