# Generated by Django 4.2.3 on 2024-06-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0007_city_geo_continent_geo_country_geo_location_geo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="country",
                to="geo.currency",
            ),
        ),
    ]
