# Generated by Django 4.2.3 on 2024-06-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0008_alter_country_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("native_name", models.CharField(max_length=256)),
                ("alpha_2_code", models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="country",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="languages", to="geo.language"
            ),
        ),
    ]
